import praw
from datetime import datetime

reddit = praw.Reddit(
    client_id = "***",
    client_secret = "****",
    user_agent = "test-script",
)
subreddit_name = "subreddit_name"

class Holidays_post():
    def __init__(self):
        self.subreddit = reddit.subreddit(subreddit_name)
        self.current_datetime = datetime.now()
        self.formatted_date = self.current_datetime.strftime("%b: %d")
        self.Holiday()

    def Holiday(self):
        Holidays = {
            "Jan: 01":"New Year's Day",
            "Jan: 02":"New Year's Day (substitute)",
            "Jan: 03":"Asarah B'Tevet",
            "Jan: 06":"Epiphany",
            "Jan: 07":["Orthodox Christmas Day","Estelle Reel Day"],
            "Jan: 08":"Battle of New Orleans",
            "Jan: 13":"Stephen Foster Memorial Day",
            "Jan: 14":"Orthodox New Year",
            "Jan: 16":["Martin Luther King Jr. Day","Robert E. Lee's Birthday","Idaho Human Rights Day","Civil Rights Day"],
            "Jan: 19":["Robert E. Lee's Birthday","State Holiday","Confederate Heroes' Day"],
            "Jan: 22":"Lunar New Year",
            "Jan: 29":"Kansas Day",
            "Feb: 01":["National Freedom Day", "National Girls and Women in Sports Day", "First Day of Black History Month"],
            "Feb: 02":"Groundhog Day",
            "Feb: 03":"National Wear Red Day",
            "Feb: 04":["Rosa Parks Day","Rosa Parks Day"],
            "Feb: 06":["Tu Bishvat/Tu B'Shevat","Ronald Reagan Day"],
            "Feb: 12":["Lincoln's Birthday","Lincoln's Birthday","Georgia Day","Super Bowl"],
            "Feb: 13":"Lincoln's Birthday observed",
            "Feb: 14":["Valentine's Day","Statehood Day"],
            "Feb: 15":"Susan B. Anthony's Birthday",
            "Feb: 16":"Elizabeth Peratrovich Day",
            "Feb: 18":["Maha Shivaratri","Isra and Mi'raj"],
            "Feb: 20":["Presidents' Day","Daisy Gatson Bates Day"],
            "Feb: 21":"Shrove Tuesday/Mardi Gras",
            "Feb: 22":"Ash Wednesday",
            "Feb: 25":["African-American Scientist and Inventor Day","George Rogers Clark Day"],
            "Feb: 28":"Linus Pauling Day",
            "Mar: 01":["St. David's Day", "Self-Injury Awareness Day"],
            "Mar: 02":"Read Across America Day",
            "Mar: 03":"Employee Appreciation Day",
            "Mar: 04":"Casimir Pulaski Day",
            "Mar: 06":"Casimir Pulaski Day",
            "Mar: 07":["Holi","Purim","Town Meeting Day"],
            "Mar: 08":["International Women's Day", "Commonwealth Day"],
            "Mar: 12":"Daylight Saving Time starts",
            "Mar: 14":"Pi Day",
            "Mar: 17":"St. Patrick's Day",
            "Mar: 20":["International Day of Happiness", "Spring Equinox"],
            "Mar: 21":"International Day for the Elimination of Racial Discrimination",
            "Mar: 23":"Ramadan Starts",
            "Mar: 25":"International Day of Remembrance of the Victims of Slavery and the Transatlantic Slave Trade",
            "Mar: 26":"Prince Jonah Kuhio Kalanianaole Day",
            "Mar: 27":["Prince Jonah Kuhio Kalanianaole Day observed","Seward's Day"],
            "Mar: 29":"National Vietnam War Veterans Day",
            "Mar: 30":["Wyoming Veterans Welcome Home Day","Doctors' Day","Vietnam Veterans Day"],
            "Apr: 02":["Palm Sunday","Pascua Florida Day"],
            "Apr: 03":"Pascua Florida Day observed",
            "Apr: 05":"Passover Eve",
            "Apr: 06":["Maundy Thursday","Passover (first day)","National Tartan Day"],
            "Apr: 07":["Good Friday","State Holiday"],
            "Apr: 08":"Holy Saturday",
            "Apr: 09":"Easter Sunday",
            "Apr: 10":"Easter Monday",
            "Apr: 13":["Last Day of Passover","Thomas Jefferson's Birthday"],
            "Apr: 14":"Orthodox Good Friday",
            "Apr: 15":["Orthodox Holy Saturday","Father Damien Day","Orthodox Easter","Emancipation Day"],
            "Apr: 17":["Lailat al-Qadr","Orthodox Easter Monday","Emancipation Day observed","Patriots' Day","Boston Marathon"],
            "Apr: 18":["Yom HaShoah","Tax Day"],
            "Apr: 21":["Eid al-Fitr","San Jacinto Day","Arbor Day"],
            "Apr: 22":"Oklahoma Day",
            "Apr: 24":["Arbor Day","Confederate Memorial Day"],
            "Apr: 25":"National Library Workers' Day",
            "Apr: 26":["Yom Ha'atzmaut","Confederate Memorial Day","State Holiday","Administrative Professionals Day"],
            "Apr: 27":"Take our Daughters and Sons to Work Day",
            "Apr: 28":"Arbor Day",
            "May: 01":["Law Day","Loyalty Day","Lei Day","First Day of Military Appreciation Month","First Day of Asian Pacific American Heritage Month","First Day of Jewish American Heritage Month"],
            "May: 02":"National Teacher Appreciation Day",
            "May: 04":["Kent State Shootings Remembrance","National Day of Prayer","Rhode Island Independence Day","West Virginia Day of Prayer"],
            "May: 05":["Cinco de Mayo","Kentucky Oaks"],
            "May: 06":["Kentucky Derby","National Nurses Day","National Explosive Ordnance Disposal (EOD) Day"],
            "May: 08":["Truman Day","Victory in Europe Day"],
            "May: 09":"Lag BaOmer",
            "May: 10":"Confederate Memorial Day",
            "May: 12":["Native American Day","Military Spouse Appreciation Day"],
            "May: 14":"Mother's Day",
            "May: 15":"Peace Officers Memorial Day",
            "May: 18":"Ascension Day",
            "May: 19":"National Defense Transportation Day",
            "May: 20":["Public Lands Day","Armed Forces Day","Preakness Stakes"],
            "May: 22":["National Maritime Day","Harvey Milk Day"],
            "May: 24":"Emergency Medical Services for Children Day",
            "May: 25":"National Missing Children's Day",
            "May: 26":"Shavuot",
            "May: 28":"Pentecost",
            "May: 29":["Whit Monday","Memorial Day","Decoration Day","Jefferson Davis' Birthday"],
            "Jun: 01":["First Day of Pride Month","First Day of Caribbean-American Heritage Month","Statehood Day"],
            "Jun: 03":"Jefferson Davis' Birthday",
            "Jun: 04":["Trinity Sunday","Native American Day"],
            "Jun: 05":"Jefferson Davis' Birthday",
            "Jun: 06":"D-Day",
            "Jun: 08":"Corpus Christi",
            "Jun: 10":"Belmont Stakes",
            "Jun: 11":"Kamehameha Day",
            "Jun: 12":["Kamehameha Day observed","Loving Day"],
            "Jun: 14":["Army Birthday","Flag Day"],
            "Jun: 16":["Juneteenth","Juneteenth Day"],
            "Jun: 17":["Bunker Hill Day","Juneteenth Day"],
            "Jun: 18":"Father's Day",
            "Jun: 19":["Juneteenth","Juneteenth National Freedom Day","Juneteenth National Freedom Day","Juneteenth","	Juneteenth Independence Day","Emancipation Day"],
            "Jun: 20":["West Virginia Day","American Eagle Day"],
            "Jun: 21":["June Solstice"],
            "Jun: 28":["Eid al-Adha","Carolina Day"],
            "Jul: 03":"Independence Day Holiday",
            "Jul: 04":"Independence Day",
            "Jul: 13":"Nathan Bedford Forrest Day",
            "Jul: 14":"Bastille Day",
            "Jul: 16":"Rural Transit Day",
            "Jul: 19":"Muharram",
            "Jul: 23":"Parents' Day",
            "Jul: 24":"Pioneer Day",
            "Jul: 27":["Tisha B'Av","Korean War Veteran Recognition Day","National Korean War Veterans Armistice Day"],
            "Jul: 28":["Ashura"],
            "Aug: 01":"Colorado Day",
            "Aug: 04":["Coast Guard Birthday","Barack Obama Day"],
            "Aug: 06":"	American Family Day",
            "Aug: 07":"Purple Heart Day",
            "Aug: 14":"Victory Day",
            "Aug: 15":"Assumption of Mary",
            "Aug: 16":"Bennington Battle Day",
            "Aug: 18":"Hawaii Statehood Day",
            "Aug: 19":"Augyland Day",
            "Aug: 20":["National Navajo Code Talkers Day","	National Senior Citizens Day"],
            "Aug: 26":["Susan B. Anthony Day","Women's Equality Day"],
            "Aug: 27":"Raksha Bandhan",
            "Sep: 04":"Labor Day",
            "Sep: 06":"Janmashtami",
            "Sep: 09":["Carl Garner Federal Lands Cleanup Day","Native American Day","California Admission Day"],
            "Sep: 10":"National Grandparents Day",
            "Sep: 11":["First Responders Day","Patriot Day"],
            "Sep: 15":["First Day of National Hispanic Heritage Month","National POW/MIA Recognition Day"],
            "Sep: 16":"Rosh Hashana",
            "Sep: 17":["Constitution Day and Citizenship Day","Constitution Commemoration Day"],
            "Sep: 18":["Ganesh Chaturthi","Air Force Birthday","Constitution Day and Citizenship Day observed"],
            "Sep: 22":["Emancipation Day","Native American Day","Michigan Indian Day"],
            "Sep: 23":["Public Lands Day","National Public Lands Day","September Equinox"],
            "Sep: 24":"Gold Star Mother's Day",
            "Sep: 25":["Yom Kippur","American Indian Day"],
            "Sep: 27":"The Prophet's Birthday",
            "Sep: 29":"American Indian Heritage Day",
            "Sep: 30":"First Day of Sukkot",
            "Oct: 02":["Frances Xavier Cabrini Day","Child Health Day"],
            "Oct: 04":"Feast of St Francis of Assisi",
            "Oct: 06":["Last Day of Sukkot","German American Day"],
            "Oct: 08":["Simchat Torah","Chicago Marathon (Tentative Date)"],
            "Oct: 09":["Leif Erikson Day","Columbus Day","Columbus Day","Fraternal Day","Yorktown Victory Day","Discoverers Day","Native American Day","Indigenous People's Day","	Indigenous People's Day (Tentative Date)","American Indian Heritage Day"],
            "Oct: 11":"Casimir Pulaski Day",
            "Oct: 13":"Navy Birthday",
            "Oct: 14":"Robert E. Lee's Birthday",
            "Oct: 15":["Navratri","White Cane Safety Day"],
            "Oct: 16":"Boss's Day",
            "Oct: 18":"Alaska Day",
            "Oct: 21":"Sweetest Day",
            "Oct: 23":"Dussehra",
            "Oct: 27":"Nevada Day",
            "Oct: 31":"Halloween",
            "Nov: 01":["All Saints' Day","First Day of Native American Heritage Month"],
            "Nov: 02":"All Souls' Day",
            "Nov: 05":["New York City Marathon","Daylight Saving Time ends"],
            "Nov: 07":"Election Day",
            "Nov: 10":["Marine Corps Birthday","Veterans Day (substitute)"],
            "Nov: 11":"Veterans Day (substitute)",
            "Nov: 12":"Diwali/Deepavali",
            "Nov: 13":["Barack Obama Day","Veterans' Day/Armistice Day (substitute)"],
            "Nov: 19":"George Rogers Clark Day",
            "Nov: 23":"Thanksgiving Day",
            "Nov: 24":["State Holiday","Presidents' Day","Lincoln's Birthday/Lincoln's Day","Day After Thanksgiving","Black Friday","American Indian Heritage Day","Native American Heritage Day"],
            "Nov: 27":"Cyber Monday",
            "Nov: 28":"Giving Tuesday",
            "Nov: 29":"Nellie Tayloe Ross's Birthday",
            "Dec: 01":"Rosa Parks Day",
            "Dec: 03":"First Sunday of Advent",
            "Dec: 06":"St Nicholas Day",
            "Dec: 07":["Pearl Harbor Remembrance Day","Pearl Harbor Remembrance Day","Delaware Day"],
            "Dec: 08":["Feast of the Immaculate Conception","Chanukah/Hanukkah (first day)"],
            "Dec: 10":"Wyoming Day",
            "Dec: 12":"Feast of Our Lady of Guadalupe",
            "Dec: 13":"National Guard Birthday",
            "Dec: 15":["Last Day of Chanukah","Bill of Rights Day"],
            "Dec: 17":["Pan American Aviation Day","Wright Brothers Day"],
            "Dec: 21":"December Solstice",
            "Dec: 22":"Asarah B'Tevet",
            "Dec: 24":"Christmas Eve",
            "Dec: 25":["Christmas Day","Christmas Eve observed"],
            "Dec: 26":["Kwanzaa (first day)","Day After Christmas Day"],
            "Dec: 31":"New Year's Eve"
        }
        try:
            return Holidays[str(self.formatted_date)]
            self.title = str(self.formatted_date) + " " + self.Holiday()
            self.subreddit.submit(self.title, selftext="")
        except:
            print("No holidays today!")
        print("Done! " + self.formatted_date)

post = Holidays_post()
